"""Generate the project site under docs/, which GitHub Pages serves from main.

One page and a privacy policy, from the templates below. Written by a script
rather than by hand so the two pages cannot drift apart, and so the colours stay
the ones the app actually uses - they are copied from
app/src/main/java/com/jemcik/jemrec/ui/theme/Theme.kt.

Run from anywhere:  python3 tools/build_site.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

REPO = "https://github.com/jemcik/JemRec"
TAGLINE = "A call recorder for unrooted Android."

CSS = """/* Generated by tools/build_site.py - edit there, not here. */

:root {
  --surface:  #FBFCFE;
  --raise:    #EEF1F6;
  --line:     #D6DCE5;
  --ink:      #161A20;
  --ink-mid:  #4C555F;
  --accent:   #2C5AA0;
  --record:   #C0392F;
  --play:     #14713C;
  --code-bg:  #F2F4F8;
  --wrap:     44rem;
  --body: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}

@media (prefers-color-scheme: dark) {
  :root {
    --surface: #101418;
    --raise:   #1A2027;
    --line:    #2C343D;
    --ink:     #E7EBF0;
    --ink-mid: #A8B2BD;
    --accent:  #8AB4F8;
    --record:  #E8564B;
    --play:    #6FDF9B;
    --code-bg: #171D24;
  }
}

* { box-sizing: border-box; }
html { font-size: 17px; scroll-behavior: smooth; }
body {
  margin: 0;
  font-family: var(--body);
  line-height: 1.62;
  color: var(--ink);
  background: var(--surface);
  -webkit-font-smoothing: antialiased;
}

.bar {
  display: flex; align-items: center; justify-content: space-between;
  gap: 1rem; padding: .9rem 1.4rem;
  border-bottom: 1px solid var(--line);
  position: sticky; top: 0; background: var(--surface); z-index: 5;
}
.brand { display: flex; align-items: center; gap: .6rem; font-weight: 700;
         color: var(--ink); text-decoration: none; font-size: 1.05rem; }
.brand img { border-radius: 22%; }
.bar nav a { color: var(--ink-mid); text-decoration: none; margin-left: 1.1rem;
             font-size: .92rem; }
.bar nav a:hover { color: var(--accent); }

main { max-width: var(--wrap); margin: 0 auto; padding: 2.6rem 1.4rem 5rem; }

h1 { font-size: 2.1rem; line-height: 1.18; letter-spacing: -.02em; margin: 0 0 .8rem; }
h2 { font-size: 1.28rem; margin: 2.6rem 0 .7rem; letter-spacing: -.01em; }
h3 { font-size: 1.02rem; margin: 1.6rem 0 .4rem; }
p  { margin: .7rem 0; }
a  { color: var(--accent); }
.lead { font-size: 1.1rem; color: var(--ink-mid); }
.muted { color: var(--ink-mid); font-size: .93rem; }

.cta { display: flex; flex-wrap: wrap; gap: .7rem; margin: 1.6rem 0 .6rem; }
.btn {
  display: inline-block; padding: .62rem 1.15rem; border-radius: 999px;
  background: var(--accent); color: var(--surface); text-decoration: none;
  font-weight: 600; font-size: .96rem; border: 1px solid transparent;
}
.btn.ghost { background: transparent; color: var(--accent); border-color: var(--line); }
.btn:hover { filter: brightness(1.06); }

.shots {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: .8rem; margin: 2.2rem 0 .6rem;
}
.shots img {
  width: 100%; height: auto; display: block;
  border: 1px solid var(--line); border-radius: 14px;
}

pre {
  background: var(--code-bg); border: 1px solid var(--line); border-radius: 10px;
  padding: .8rem 1rem; overflow-x: auto; font-size: .86rem; line-height: 1.5;
}
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .88em; }
p code, li code { background: var(--code-bg); padding: .1rem .32rem; border-radius: 5px; }

table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: .94rem; }
th, td { text-align: left; padding: .5rem .7rem; border-bottom: 1px solid var(--line);
         vertical-align: top; }
th { color: var(--ink-mid); font-weight: 600; }

.note {
  border-left: 3px solid var(--record); background: var(--raise);
  padding: .8rem 1rem; border-radius: 0 10px 10px 0; margin: 1.4rem 0;
}
.note strong { color: var(--ink); }

footer {
  border-top: 1px solid var(--line); margin-top: 3rem; padding: 1.6rem 1.4rem 3rem;
  color: var(--ink-mid); font-size: .9rem; text-align: center;
}
footer a { color: var(--ink-mid); }
"""


def page(title: str, description: str, body: str, here: str) -> str:
    def nav(href: str, label: str) -> str:
        current = ' aria-current="page"' if href == here else ""
        return f'<a href="{href}"{current}>{label}</a>'

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="color-scheme" content="light dark">
<link rel="icon" href="icon.png">
<link rel="stylesheet" href="jemrec.css">
</head>
<body>
<header class="bar">
  <a class="brand" href="index.html"><img src="icon.png" alt="" width="34" height="34">JemRec</a>
  <nav>{nav("index.html", "Home")}{nav("privacy-policy.html", "Privacy")}<a href="{REPO}">GitHub</a></nav>
</header>
<main>
{body}
</main>
<footer>
  <p>JemRec is free software under the Apache&nbsp;2.0 licence.
     <a href="{REPO}">Source on GitHub</a>.</p>
</footer>
</body>
</html>
"""


INDEX_BODY = f"""
  <h1>{TAGLINE}</h1>
  <p class="lead">One APK. No root, no Shizuku, no companion app, and no computer
     &mdash; the phone pairs with its own Wireless debugging and sets itself up.</p>

  <div class="cta">
    <a class="btn" href="{REPO}/releases">Download the APK</a>
    <a class="btn ghost" href="{REPO}">Source on GitHub</a>
  </div>
  <p class="muted">Android 12 or newer. Not on Google Play, and never will be.</p>

  <div class="shots">
    <img src="screenshots/home.png" alt="The recordings list" loading="lazy">
    <img src="screenshots/home-dark.png" alt="The recordings list, dark" loading="lazy">
    <img src="screenshots/settings.png" alt="Settings" loading="lazy">
    <img src="screenshots/selftest-dark.png" alt="The self-test" loading="lazy">
  </div>
  <p class="muted">The people in those screenshots do not exist: a screenshot of a
     call recorder is a screenshot of someone&rsquo;s calls, so the list is filled
     with invented ones. Everything above the list is real.</p>

  <h2>How it works</h2>

  <p>Android&rsquo;s <code>voice-call</code> audio source carries both sides of a
     call, and reading it needs permissions no ordinary app can hold &mdash; but
     the shell user, the one an ADB session runs as, holds them. Getting shell
     privilege normally means a computer, or root, or a second app you keep
     alive. JemRec needs none of them, because the phone can be its own
     computer.</p>

  <h3>The phone is both ADB host and ADB device</h3>
  <p>The app embeds an ADB client and pairs, over <code>127.0.0.1</code>, with
     the phone&rsquo;s own Wireless debugging &mdash; the same six-digit pairing a
     laptop does, with both ends on the same handset. Nothing leaves the phone.</p>

  <h3>ADB is a bootstrap, not a transport</h3>
  <p>That session lasts seconds. In it the app grants itself one settings
     permission and launches a small daemon from a jar it carries inside the APK,
     then closes the session. A process started from an ADB shell outlives the
     connection, which is the whole trick: with Wi-Fi off there is no ADB at all,
     so anything that needed it when a call arrived would simply not record.</p>

  <h3>The daemon records; the app collects</h3>
  <p>The daemon watches the call state and writes the call to a file. The app is
     never on the audio path. That split was forced by measurement: when the app
     handled live audio, the phone&rsquo;s process manager froze it while the
     dialer was in front and a 77-second call arrived as 14. Afterwards the app
     fetches the finished file at whatever pace the system allows, and a freeze
     there costs a slower copy rather than a lost second.</p>

  <h3>The socket is authenticated both ways</h3>
  <p>The daemon listens on loopback, which every process on the phone shares, so
     each connection proves itself with an HMAC exchange over a token that never
     crosses the socket. The daemon proves itself first &mdash; anything can bind
     that port while the daemon is down, and a scheme that sent the token as a
     password would hand it over.</p>

  <h3>It keeps itself alive</h3>
  <p>Losing Wi-Fi restarts the ADB daemon and kills what it spawned, so the
     recorder keeps one debugging switch on to survive it, and minds that switch
     itself. When it does die &mdash; a reboot, or the system reclaiming it &mdash;
     a scheduled job and a Wi-Fi watcher rebuild it the moment there is a network
     to do it over. Recording needs no network; only rebuilding does.</p>

  <h2>What it asks for, and what it does not</h2>
  <p>No microphone permission. The app never opens an audio device &mdash; the
     shell-side process does the capturing &mdash; and a call recorder that asks
     for the microphone anyway is asking for something it does not use. Reading
     your call log and contacts is optional, offered once, and only labels a
     recording with who the call was with.</p>

  <div class="note">
    <p><strong>Recording calls is your responsibility.</strong> Consent law
       differs by country and sometimes by state: one party, all parties, or a
       spoken notice. This app records what you tell it to and warns nobody on
       your behalf.</p>
  </div>

  <h2>Will it work on your phone?</h2>
  <p>One thing cannot be worked around: whether your phone&rsquo;s audio hardware
     hands over the call at all. Some give both sides, some give one, some give
     silence. JemRec answers it in about a second &mdash; Settings, Diagnostics,
     <strong>Self-test</strong> &mdash; by opening a real capture down the same
     path a call takes and telling you what came out.</p>
  <p class="muted">Developed and verified on an Honor Magic&nbsp;8 Pro
     (MagicOS&nbsp;10, Android&nbsp;16).</p>
"""

PRIVACY_BODY = f"""
  <h1>Privacy policy</h1>
  <p class="lead">JemRec has no servers, no accounts, and no analytics. Nothing it
     records or reads ever leaves your phone.</p>
  <p class="muted">Last updated: September 2026.</p>

  <h2>What it collects</h2>
  <p><strong>Nothing is sent anywhere.</strong> There is no backend to send it to.
     The developer cannot see your recordings, your contacts, your call history,
     or that you use the app at all.</p>

  <h2>What stays on the phone</h2>
  <table>
    <tr><th>Data</th><th>Where it lives</th></tr>
    <tr><td>Call recordings</td>
        <td>The phone&rsquo;s <code>Recordings/JemRec</code> folder, or a folder you
            choose. Yours to play, share, move or delete like any other file.</td></tr>
    <tr><td>Contact names and photos</td>
        <td>Read from the phone&rsquo;s own call log and contacts, only if you
            allow it, and only to label a recording. Nothing is copied or stored;
            the lookup happens each time the list is shown.</td></tr>
    <tr><td>Settings</td>
        <td>The app&rsquo;s own private storage: whether recording is on, whether to
            ask before each call, where to save, and a random token the app uses to
            talk to its own recorder.</td></tr>
  </table>

  <h2>Network use</h2>
  <p>The app holds the <code>INTERNET</code> permission and uses no network. Android
     requires that permission for <em>any</em> TCP socket, including one to
     <code>127.0.0.1</code>, and the app&rsquo;s two sockets are both to the phone
     itself: pairing with the phone&rsquo;s own Wireless debugging during setup, and
     talking to its recorder afterwards. Neither reaches your router, let alone the
     internet.</p>

  <h2>The microphone</h2>
  <p>The app holds no microphone permission and opens no audio device. Calls are
     captured by a separate shell-privileged process, which the app starts during
     setup and which writes to a file the app collects afterwards.</p>

  <h2>Deleting your data</h2>
  <p>Delete individual recordings in the app, or the whole folder from any file
     manager. <em>Start fresh</em> in Settings undoes the setup and hands the
     permissions back, and deliberately keeps your recordings. Uninstalling the app
     removes the app and its settings; the recordings stay, because they are yours
     and are not the app&rsquo;s to take.</p>

  <h2>Children</h2>
  <p>The app is not directed at children and collects nothing from anyone.</p>

  <h2>Changes</h2>
  <p>If this policy ever changes it changes
     <a href="{REPO}/blob/main/tools/build_site.py">in the open</a>, in the same
     repository as the code, with the change visible in the history.</p>

  <h2>Contact</h2>
  <p>Questions and bug reports: <a href="{REPO}/issues">GitHub issues</a>.</p>
"""


if __name__ == "__main__":
    DOCS.mkdir(parents=True, exist_ok=True)
    # Pages runs Jekyll by default, which ignores files beginning with an
    # underscore and would rather render Markdown than serve it. Nothing here
    # needs Jekyll.
    (DOCS / ".nojekyll").write_text("")
    (DOCS / "jemrec.css").write_text(CSS)
    (DOCS / "index.html").write_text(
        page(f"JemRec · {TAGLINE}", TAGLINE, INDEX_BODY, "index.html")
    )
    (DOCS / "privacy-policy.html").write_text(
        page(
            "JemRec · Privacy policy",
            "JemRec has no servers and no analytics: nothing leaves your phone.",
            PRIVACY_BODY,
            "privacy-policy.html",
        )
    )
    for name in (".nojekyll", "jemrec.css", "index.html", "privacy-policy.html"):
        print(f"wrote docs/{name}")
