"""Generate the project site under docs/, which GitHub Pages serves from main.

One page and a privacy policy, from the templates below. Written by a script
rather than by hand so the two pages cannot drift apart, and so the colours stay
the ones the app actually uses - they are taken from
app/src/main/java/com/jemcik/jemrec/ui/theme/Theme.kt and then lifted slightly,
for the reason written above the palette.

Run from anywhere:  python3 tools/build_site.py
"""
import pathlib
import re
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

REPO = "https://github.com/jemcik/JemRec"
TAGLINE = "A call recorder for unrooted Android."

# THE THEME HAS THREE STATES, NOT TWO, and the palette is written twice because
# of it:
#
#   bare :root                          light, and the default
#   @media (prefers-color-scheme: dark) the reader's system says dark
#   :root[data-theme=...]               the reader pressed the button
#
# The media query is guarded with :not([data-theme="light"]) so that choosing
# light on a system set to dark actually wins, and the stamped rule comes last
# so it beats both. The values live here rather than in the stylesheet text so
# the two copies cannot drift.
DARK_VARS = """    --surface: #22262B;
    --raise:   #2C3137;
    --line:    #3B4149;
    --ink:     #E4E7EB;
    --ink-mid: #B2BAC4;
    --accent:  #9ECAFF;
    --record:  #FF7A6B;
    --play:    #6FDF9B;
    --code-bg: #1B1F23;"""

CSS = """/* Generated by tools/build_site.py - edit there, not here. */

/* NEITHER END IS TAKEN TO ITS EXTREME. The app's own dark surface is #1A1C1E,
   which is right on a phone held at night and reads as a black page in a browser
   window - and it was darker than the phone screenshots lying on it, so every
   image glowed like a light box. The light end started at #FBFCFE, near enough
   to paper that the cards on it had nothing to lift off. So the page sits a step
   in from both: a soft grey-blue in light, a lifted charcoal in dark, with the
   cards and the code blocks moving the other way in each. */
:root {
  --surface:  #F1F4F8;
  --raise:    #FAFBFD;
  --line:     #D5DCE5;
  --ink:      #161A20;
  --ink-mid:  #4C555F;
  --accent:   #2C5AA0;
  --record:   #C0392F;
  --play:     #14713C;
  --code-bg:  #E7ECF3;
  --wrap:     44rem;
  --body: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
__DARK__
  }
}

:root[data-theme="dark"] {
__DARK__
}

* { box-sizing: border-box; }
html { font-size: 17px; scroll-behavior: smooth; }
body {
  margin: 0;
  font-family: var(--body);
  line-height: 1.62;
  color: var(--ink);
  background: var(--surface);
  -webkit-font-smoothing: antialiased;
}

/* The RULE spans the window; the CONTENT does not. A sticky bar whose border
   stops short of the edges reads as a floating card rather than a header, so
   the bar stays full width and everything inside it sits in the same column as
   the prose - same max-width, same side padding, so the wordmark starts exactly
   where the headline does. */
.bar {
  padding: .9rem 0;
  border-bottom: 1px solid var(--line);
  position: sticky; top: 0; background: var(--surface); z-index: 5;
}
.column { max-width: var(--wrap); margin: 0 auto; padding: 0 1.4rem; }
.bar .column {
  display: flex; align-items: center; justify-content: space-between; gap: 1rem;
}
.brand { display: flex; align-items: center; gap: .6rem; font-weight: 700;
         color: var(--ink); text-decoration: none; font-size: 1.05rem; }
.brand img { border-radius: 22%; }
.bar-end { display: flex; align-items: center; gap: .9rem; }
.bar nav a { color: var(--ink-mid); text-decoration: none; margin-left: 1.1rem;
             font-size: .92rem; }
.bar nav a:first-child { margin-left: 0; }
.bar nav a:hover { color: var(--accent); }

.theme {
  display: inline-flex; align-items: center; gap: .35rem;
  font: inherit; font-size: .92rem; color: var(--ink-mid);
  background: var(--raise); border: 1px solid var(--line); border-radius: 999px;
  padding: .2rem .66rem; cursor: pointer;
}
.theme:hover { color: var(--accent); border-color: var(--accent); }
.theme svg { width: 14px; height: 14px; }
/* The word goes before the button does. Below this the wordmark, three links and
   a labelled button do not fit on one line, and a masthead that wraps to two
   looks broken rather than responsive. */
@media (max-width: 32rem) {
  .theme .theme-name { display: none; }
  .bar nav a { margin-left: .85rem; }
  .bar-end { gap: .6rem; }
}

main { max-width: var(--wrap); margin: 0 auto; padding: 2.6rem 1.4rem 5rem; }

h1 { font-size: 2.1rem; line-height: 1.18; letter-spacing: -.02em; margin: 0 0 .8rem; }
h2 { font-size: 1.28rem; margin: 2.6rem 0 .7rem; letter-spacing: -.01em; }
h3 { font-size: 1.02rem; margin: 1.6rem 0 .4rem; }
p  { margin: .7rem 0; }
a  { color: var(--accent); }
.lead { font-size: 1.1rem; color: var(--ink-mid); }
.muted { color: var(--ink-mid); font-size: .93rem; }

.cta { display: flex; flex-wrap: wrap; gap: .7rem; margin: 1.6rem 0 .6rem; }
.btn {
  display: inline-block; padding: .62rem 1.15rem; border-radius: 999px;
  background: var(--accent); color: var(--surface); text-decoration: none;
  font-weight: 600; font-size: .96rem; border: 1px solid transparent;
}
.btn.ghost { background: var(--raise); color: var(--accent); border-color: var(--line); }
.btn:hover { filter: brightness(1.06); }

.shots {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: .8rem; margin: 2.2rem 0 .6rem;
}
.shot {
  padding: 0; border: 1px solid var(--line); border-radius: 14px;
  background: var(--raise); cursor: zoom-in; overflow: hidden; display: block;
}
.shot img { width: 100%; height: auto; display: block; }
.shot:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }

pre {
  background: var(--code-bg); border: 1px solid var(--line); border-radius: 10px;
  padding: .8rem 1rem; overflow-x: auto; font-size: .86rem; line-height: 1.5;
}
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .88em; }
p code, li code { background: var(--code-bg); padding: .1rem .32rem; border-radius: 5px; }

table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: .94rem; }
th, td { text-align: left; padding: .5rem .7rem; border-bottom: 1px solid var(--line);
         vertical-align: top; }
th { color: var(--ink-mid); font-weight: 600; }

.note {
  border-left: 3px solid var(--record); background: var(--raise);
  padding: .8rem 1rem; border-radius: 0 10px 10px 0; margin: 1.4rem 0;
}
/* Two callouts on one page, and they are not the same kind of thing: one is a
   warning about the law, the other is a fact about how the app behaves. The
   accent keeps the second from reading as a second alarm. */
.note.info { border-left-color: var(--accent); }
.note strong { color: var(--ink); }

footer {
  border-top: 1px solid var(--line); margin-top: 3rem; padding: 1.6rem 0 3rem;
  color: var(--ink-mid); font-size: .9rem; text-align: center;
}
footer a { color: var(--ink-mid); }

/* ── the screenshot viewer ── */

.viewer {
  position: fixed; inset: 0; z-index: 50;
  background: rgba(0, 0, 0, .82);
  display: flex; align-items: center; justify-content: center;
  padding: 2rem 1rem; cursor: zoom-out;
}
.viewer[hidden] { display: none; }
.viewer img {
  max-width: min(92vw, 420px); max-height: 92vh;
  border-radius: 14px; box-shadow: 0 24px 60px rgba(0, 0, 0, .5);
}
/* FITTING THE HEIGHT STOPS BEING AN ENLARGEMENT ON A SHORT WINDOW. These are
   phone screenshots at roughly 1:2.24 and the thumbnail is already ~230px wide,
   so in a docked browser pane 92vh can be SMALLER than the picture that was
   clicked. Below that point, size by width and let the overlay scroll -
   flex-start rather than centre, or the overflowing top cannot be reached. */
@media (max-height: 780px) {
  .viewer { align-items: flex-start; overflow: auto; }
}
.vnav {
  position: fixed; top: 50%; transform: translateY(-50%);
  width: 46px; height: 46px; border-radius: 50%;
  border: none; background: rgba(255, 255, 255, .14); color: #fff;
  font-size: 1.6rem; line-height: 1; cursor: pointer;
}
.vnav:hover { background: rgba(255, 255, 255, .26); }
/* Beside the picture where there is room for them, at the window's edge where
   there is not: the image is capped at 420px, so past a ~1000px window the
   arrows can sit outside it, and below that they overlap it. */
.vnav.prev { left: max(.6rem, calc(50vw - min(46vw, 210px) - 62px)); }
.vnav.next { right: max(.6rem, calc(50vw - min(46vw, 210px) - 62px)); }
.viewer.solo .vnav { display: none; }
.vcount {
  position: fixed; bottom: 1.2rem; left: 0; right: 0; text-align: center;
  color: rgba(255, 255, 255, .75); font-size: .85rem;
}
.viewer.solo .vcount { display: none; }
"""

JS = """// Generated by tools/build_site.py - edit there, not here.
(function () {
  var KEY = 'jemrec-theme', ORDER = ['system', 'light', 'dark'];

  function read() {
    try { return localStorage.getItem(KEY) || 'system'; } catch (e) { return 'system'; }
  }
  function apply(v) {
    var r = document.documentElement;
    if (v === 'system') r.removeAttribute('data-theme');
    else r.setAttribute('data-theme', v);
  }
  function label(btn, v) {
    var name = v.charAt(0).toUpperCase() + v.slice(1);
    btn.setAttribute('aria-label', 'Theme: ' + name + '. Click to change.');
    btn.querySelector('.theme-name').textContent = name;
  }

  document.addEventListener('DOMContentLoaded', function () {
    var btn = document.querySelector('.theme');
    if (btn) {
      var cur = read();
      label(btn, cur);
      btn.addEventListener('click', function () {
        cur = ORDER[(ORDER.indexOf(cur) + 1) % ORDER.length];
        try { localStorage.setItem(KEY, cur); } catch (e) {}
        apply(cur);
        label(btn, cur);
      });
    }

    // Click a screenshot to see it properly. The thumbnail on the page is a
    // 420px copy; the viewer loads the full capture, which is the only place it
    // is worth a quarter of a megabyte. Escape closes, and so does clicking
    // anywhere - the whole overlay is the target, because hunting for a small
    // cross is the thing people complain about.
    //
    // It is a GALLERY: once one is open the arrows and the left and right keys
    // move through the set without closing it. Closing and reopening to see the
    // next of four is what makes a lightbox feel like a document viewer.
    var viewer = document.querySelector('.viewer');
    var shots = [].slice.call(document.querySelectorAll('.shot'));
    if (!viewer || !shots.length) return;

    var img = viewer.querySelector('img');
    var count = viewer.querySelector('.vcount');
    var at = -1;

    // Neighbours are fetched ahead: these are 250kB captures, and without it
    // every arrow press blanks the overlay while the next one loads.
    function warm(i) {
      [i - 1, i + 1].forEach(function (n) {
        var b = shots[(n + shots.length) % shots.length];
        if (b) { new Image().src = b.dataset.full; }
      });
    }
    function show(i) {
      at = (i + shots.length) % shots.length;
      var b = shots[at];
      img.src = b.dataset.full;
      img.alt = b.getAttribute('aria-label') || '';
      count.textContent = (at + 1) + ' / ' + shots.length;
      warm(at);
    }
    function step(d) { if (shots.length > 1) show(at + d); }

    // Hold the page still underneath. The overlay covers everything, so a wheel
    // over it scrolls a page nobody can see, and closing then lands somewhere
    // other than the screenshots. The padding replaces the scrollbar's own
    // width, or the whole page shifts sideways as the viewer opens.
    function lock(on) {
      var d = document.documentElement;
      if (on) {
        var gap = window.innerWidth - d.clientWidth;
        d.style.overflow = 'hidden';
        if (gap > 0) d.style.paddingRight = gap + 'px';
      } else {
        d.style.overflow = '';
        d.style.paddingRight = '';
      }
    }

    function close() {
      viewer.hidden = true;
      lock(false);
      img.removeAttribute('src');
      // Back to the thumbnail SHOWING, not the one clicked: after three arrow
      // presses the picture on screen is not the one that opened the viewer,
      // and landing the keyboard back on that one is disorienting.
      var b = shots[at];
      at = -1;
      if (b) b.focus();
    }

    viewer.classList.toggle('solo', shots.length < 2);
    shots.forEach(function (b) {
      b.addEventListener('click', function () {
        viewer.hidden = false;
        lock(true);
        show(shots.indexOf(b));
        // tabindex="-1" is what makes this line do anything: a plain div is not
        // focusable, so focus would stay on <body> and the dialog would open
        // without announcing itself.
        viewer.focus();
      });
    });
    viewer.addEventListener('click', close);
    viewer.querySelectorAll('.vnav').forEach(function (b) {
      b.addEventListener('click', function (e) {
        e.stopPropagation();  // the overlay closes on any click, and these are inside it
        step(b.classList.contains('next') ? 1 : -1);
      });
    });
    document.addEventListener('keydown', function (e) {
      if (viewer.hidden) return;
      if (e.key === 'Escape') close();
      else if (e.key === 'ArrowRight') { e.preventDefault(); step(1); }
      else if (e.key === 'ArrowLeft') { e.preventDefault(); step(-1); }
    });
  });
})();
"""

# Before the stylesheet, and not deferred: a stored choice applied on
# DOMContentLoaded lets the system's colours paint first and then swaps them,
# which is a flash of the wrong theme on every page load.
HEAD_SCRIPT = (
    "<script>(function(){try{var v=localStorage.getItem('jemrec-theme');"
    "if(v&&v!=='system')document.documentElement.setAttribute('data-theme',v);}"
    "catch(e){}})();</script>"
)

THEME_BUTTON = """<button class="theme" type="button" aria-label="Theme">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
             stroke-linecap="round" aria-hidden="true">
          <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z"/>
        </svg><span class="theme-name">System</span>
      </button>"""

VIEWER = """<div class="viewer" hidden tabindex="-1" role="dialog" aria-modal="true"
     aria-label="Screenshot">
  <button class="vnav prev" type="button" aria-label="Previous">&lsaquo;</button>
  <img alt="">
  <button class="vnav next" type="button" aria-label="Next">&rsaquo;</button>
  <span class="vcount"></span>
</div>"""


# ---------------------------------------------------------------------------
# THE SETUP MANUAL, WRITTEN ONCE.
#
# It is rendered twice: as docs/setup.html for the site and as docs/SETUP.md for
# people reading the repository. The two used to be one hand-written file with
# the site not carrying it at all, and by the time the site wanted it the file
# had drifted badly from the app - it still asked for a Phone permission that
# had been removed, never mentioned USB debugging, and described a permanent
# notification that no longer exists. A manual that lies is worse than no
# manual, and two copies of one is how it happens, so there is one copy and two
# renderers.
#
# Blocks are ("kind", payload). Inline markup is the small Markdown subset the
# text actually uses: **bold** and `code`.
# ---------------------------------------------------------------------------

SETUP_TITLE = "Setting up JemRec"
SETUP_LEAD = (
    "Everything happens on the phone. You will not need a computer, a cable, or "
    "a second app. It takes about three minutes, and you do it once."
)

SETUP = [
    ("p", "Every step below was walked through on an Honor Magic 8 Pro running "
          "MagicOS 10, and the screen names are the ones that actually appear "
          "there. Other phones differ in wording; the shape of the process does "
          "not, and JemRec names the right path for your phone as you go."),

    ("h2", "Installing"),
    ("p", "Download the APK from the project's **Releases** page and open it. "
          "Android asks whether to allow installing from whatever you opened it "
          "with — a browser, or a file manager — and that permission is granted "
          "per app, not once for the phone."),
    ("p", "**Play Protect may object, and what it takes differs by phone.** It "
          "warns about apps it has not seen before, which is every app that is "
          "not on Google Play, so this is not a judgement about JemRec. Three "
          "phones, three outcomes:"),
    ("table", (["Phone", "What happened"], [
        ["Honor Magic 8 Pro", "Installed with no complaint."],
        ["Samsung Galaxy S20",
         "Refused. Turning Play Protect off long enough to install, then back "
         "on, worked — it is in the Play Store under your profile picture → "
         "Play Protect → Settings."],
        ["OnePlus on LineageOS",
         "Refused when the download was opened from the browser. Opening the "
         "same file from the **Files** app installed it."],
    ])),
    ("p", "If yours refuses, those are the two things to try, in that order: "
          "open the file from a file manager rather than the browser, and only "
          "then consider turning Play Protect off for the minute it takes — and "
          "back on afterwards."),
    ("p", "Every release is signed with the same key, so each one installs over "
          "the one before it. If you would rather check what you downloaded than "
          "trust it, `apksigner verify --print-certs` on the file should report "
          "SHA-256 `50aeab3630f0198ea3845db51413b1ad29582f78240fa2df6fe55ba8537afdf8`, "
          "the same digest the release workflow prints in its log on every run."),

    ("h2", "Step 1 — Open JemRec and allow notifications"),
    ("ol", [
        "Open **JemRec**.",
        "It asks for **notifications**. Allow them.",
        "It also offers to read audio files, which lets it list recordings made "
        "before a reinstall. Refusing that is fine; only the old ones are hidden.",
    ]),
    ("p", "Notifications are not decoration here. They are how the app tells you "
          "a call is being recorded, how it asks whether to record one, and "
          "where you will type the pairing code in step 4."),
    ("p", "JemRec does **not** ask for microphone access and does not have it. "
          "The recording is done by a separate, more privileged helper that the "
          "app starts later; the app itself only collects the finished file."),

    ("h2", "Step 2 — Turn on Developer options"),
    ("p", "Skip this if Developer options are already on."),
    ("ol", [
        "Open **Settings**.",
        "Search for `build number`. It usually lives under **About phone**, but "
        "the path differs between phones, which is why searching beats hunting.",
        "Tap **Build number** seven times.",
        "Enter your PIN or pattern if asked.",
    ]),
    ("p", "You should see *You are now a developer*."),

    ("h2", "Step 3 — Turn on both debugging switches"),
    ("p", "**Be on Wi-Fi before you start this.** Wireless debugging only stays "
          "on while the phone has a Wi-Fi connection."),
    ("ol", [
        "In JemRec, tap **Open settings**, then search Settings for **Developer "
        "options**. The app also names the menu it usually lives in on your "
        "phone — though on a custom ROM such as LineageOS it is under "
        "**System**, whoever made the handset.",
        "Turn on **USB debugging** and **Wireless debugging**. Either order. No "
        "cable is needed and none should be plugged in.",
        "If Android asks whether to allow wireless debugging on this network, "
        "tick **Always allow** and tap **Allow**.",
        "Look at both switches once more. One of them can switch itself off the "
        "first time; turn it on again and it holds.",
    ]),
    ("p", "**Why both.** Wireless debugging is the channel JemRec uses to start "
          "its recorder. USB debugging — the setting, with no cable involved — is "
          "what keeps Android's debugging service alive, and without it Wireless "
          "debugging switches itself off again before the app can connect."),
    ("note", "If you see an old **JemRec** under *Paired devices*, tap the gear "
             "beside it and forget it. It is left over from a previous install "
             "and cannot be used: a reinstalled app has a new key and must pair "
             "again."),

    ("h2", "Step 4 — Pair, from your notifications"),
    ("p", "**Read this step before starting it.** The obvious approach does not "
          "work, and knowing why saves repeating it."),
    ("p", "The pairing dialog exists only while Settings is on screen. Leave "
          "Settings — by switching to JemRec, or by pressing Back — and Android "
          "tears the dialog down instantly, taking the code with it."),
    ("p", "The notification shade is different. It belongs to the system rather "
          "than to another app, so pulling it down leaves Settings running and "
          "the dialog intact. That is where you type the code, and JemRec posts "
          "the field before you go anywhere so it is already waiting."),
    ("ol", [
        "In JemRec, tap **Open settings**.",
        "Open **Wireless debugging**, then tap **Pair device with pairing "
        "code**. Six digits appear.",
        "**Swipe down** from the top of the screen, over that dialog.",
        "Find **JemRec — pairing** and tap **Enter code**.",
        "Type the six digits and send them.",
    ]),
    ("p", "You do not need the port number. JemRec finds that itself."),
    ("p", "Then watch that same notification. It says what is happening, and if "
          "a debugging switch turned itself off it says which one — turn it back "
          "on and the app connects by itself. There is no need to pair again or "
          "to fetch a new code."),
    ("note", "The code changes every time the dialog is reopened, so always use "
             "the one on screen. If you swiped the notification away, tap **Show "
             "the code field again** in JemRec to bring it back."),

    ("h2", "Step 5 — Wait a few seconds"),
    ("p", "JemRec does the rest by itself: it grants itself the one privileged "
          "setting it needs, starts the recorder, and begins watching for calls. "
          "When it is done the header says **Ready to record**."),
    ("p", "There is no permanent notification. The app is dormant between calls "
          "— the recorder is a separate process that does the watching — so a "
          "notification appears only for the length of a call."),

    ("h2", "Step 6 — Test it"),
    ("p", "Call someone and talk for twenty seconds, with both of you speaking."),
    ("ul", [
        "During the call a notification says **Recording call**.",
        "After you hang up, open JemRec. The recording is at the top of the list.",
    ]),
    ("p", "Files are named like `20260907_150909_out.ogg` — date, time, and `in` "
          "or `out` for the direction. They are ordinary Ogg Opus files that any "
          "player can open."),
    ("p", "If your recording has only your own voice on it, that is the one thing "
          "no app can fix: your phone's audio hardware does not hand the other "
          "side to apps at all. **Settings → Diagnostics → Self-test** answers "
          "that in about a second, without ringing anybody."),

    ("h2", "Where recordings go"),
    ("p", "The phone's standard **Recordings/JemRec** folder, which any file "
          "manager or music app can open, and which survives uninstalling the "
          "app. To use a different folder, open Settings and tap **Change** under "
          "*Saving to*."),

    ("h2", "Choosing when to record"),
    ("p", "**Record every call**, in Settings, decides this."),
    ("ul", [
        "**On**, the default: every call is recorded and you are not asked.",
        "**Off**: when a call starts a notification appears with **Record** and "
        "**Not now**. Nothing is captured until you tap Record, so the opening "
        "seconds of that call are not saved. That is the honest cost of being "
        "asked, and it is why the switch is on by default.",
    ]),
    ("p", "The prompt stays up for about a minute rather than the few seconds an "
          "ordinary notification gets, and if you miss it, it waits in the shade "
          "for the rest of the call. On a locked screen you get the same question "
          "full screen."),

    ("h2", "Playing, sharing and deleting"),
    ("p", "Tap a recording to play it inside the app; a scrubber appears under "
          "the row, and the chevron beside it folds the player away. The share "
          "button offers the original file or a converted copy that plays "
          "anywhere."),
    ("p", "To delete, tap a contact's photo or long-press a row to start "
          "selecting, tick what you want, and use the bin in the toolbar. It asks "
          "first and tells you how many. Deleting is permanent."),
    ("p", "Recordings are kept when JemRec is uninstalled, because they are yours "
          "rather than the app's — so if you want them gone, delete them **before** "
          "you uninstall."),

    ("h2", "Turning JemRec off"),
    ("p", "The switch in the header is the on/off control for the whole app. Off "
          "means no call is recorded and no notification appears. Your recordings "
          "and your pairing are untouched, and the recorder itself keeps running "
          "in the background doing nothing — which is what makes turning it back "
          "on instant, anywhere, with no network."),

    ("h2", "After a restart"),
    ("p", "A reboot kills the recorder, and building it again takes a few seconds "
          "of Wi-Fi. Until that has happened, calls are not recorded and the "
          "header says so. Whether it happens without you comes down to one "
          "setting on your phone."),
    ("h3", "Allow JemRec to start automatically"),
    ("p", "This is the fix, and it is worth doing once. JemRec's own Settings has "
          "a **Survive a restart** card with a button that opens the right screen "
          "on your phone, because the list is four levels deep and called "
          "something different on every make. On an Honor it is *Settings → "
          "Battery → App launch*; find JemRec, switch it to **Manage manually** "
          "and leave **Auto-launch** on. Xiaomi calls it Autostart, OPPO and vivo "
          "have their own. The card only appears on a phone that has such a "
          "list."),
    ("p", "What it buys, measured on that Honor: the app was started by the boot "
          "broadcast at 21 seconds of uptime, armed its scheduled job and asked "
          "the system to wake it when Wi-Fi appeared, and the recorder was back "
          "**ten seconds** after Wi-Fi came on — with the app never opened."),
    ("h3", "Without it, open JemRec once"),
    ("p", "The same phone with auto-launch off does nothing at all. The system "
          "declined to start the app for the boot broadcast — *don't meet "
          "cpuload*, in its own log — so neither the job nor the Wi-Fi watcher "
          "was ever armed, and seven minutes after Wi-Fi returned nothing had "
          "come back. Opening the app had it recording sixteen seconds later."),
    ("p", "So if you would rather not touch battery settings, treat opening "
          "JemRec once as part of restarting the phone. It always works."),
    ("p", "Either way: Wi-Fi is needed to rebuild the recorder, never to use it. "
          "Once it is up, calls are recorded with Wi-Fi off, on mobile data, "
          "anywhere."),

    ("h2", "What the app tells you"),
    ("p", "The header is the honest indicator:"),
    ("table", (["It says", "Meaning"], [
        ["**Ready to record**", "A call would be recorded right now."],
        ["**Recording call**", "In the notification, during a call."],
        ["**Cannot record, needs Wi-Fi**", "Join any Wi-Fi and it resumes on its "
         "own. Usually a reboot, or a long stretch away from a network."],
        ["**Starting…**", "Rebuilding the recorder. A few seconds."],
        ["**Off**", "You turned the switch off."],
    ])),

    ("h2", "Settings"),
    ("ul", [
        "**Record every call** — record everything, or be asked each time.",
        "**Saving to** — which folder recordings go in, with a Change button.",
        "**Show who called** — labels each recording with the contact's name and "
        "photo, or the number when they are not in your contacts. Optional, and "
        "asked for in the app rather than at install, because it needs your call "
        "log and contacts. Say no and everything still works, with the time as "
        "each recording's headline.",
        "**Start fresh** — puts JemRec back to how it was the day you installed "
        "it, so setup runs again from step 1. The app closes when you confirm. "
        "**Your recordings are not deleted.**",
        "**Diagnostics** — whether the recorder is running, a self-test that "
        "proves a call would be recorded, and a way to start the recorder by "
        "hand. It is what a bug report wants.",
    ]),

    ("h2", "If something goes wrong"),
    ("p", "**Pairing fails every time.** Almost always the dialog closed. It "
          "survives only while Settings is on screen, which is why step 4 uses "
          "the notification shade rather than switching back to the app. Reopen "
          "the dialog for a fresh code each attempt."),
    ("p", "**A debugging switch keeps turning itself off.** Some phones do that "
          "the first time one is enabled without a cable, and Android turns "
          "Wireless debugging off whenever Wi-Fi drops. Turn it on again with "
          "Wi-Fi connected; it holds the second time."),
    ("p", "**It says it cannot record.** Join any Wi-Fi and leave it a few "
          "seconds; the app rebuilds its recorder without being asked. If you "
          "would rather not wait, Settings → Diagnostics → **Start recorder**."),
    ("p", "**Recordings have only your voice.** Your phone's audio hardware does "
          "not expose the other side to apps. Nothing in any app can change that, "
          "and the self-test will tell you plainly."),

    ("h2", "Uninstalling"),
    ("p", "Uninstall it however you like — long-press the icon, or Settings → "
          "Apps. There is nothing special to do."),
    ("p", "The recorder is a separate system process rather than part of the app, "
          "so removing the package does not stop it immediately. It checks every "
          "few minutes whether JemRec is still installed, and when it is not it "
          "turns both debugging switches off, deletes its own files and exits. A "
          "reinstall is never fooled by one that has not got there yet, either: "
          "the app only trusts a recorder it started itself, and retires any "
          "other on sight."),
    ("note", "**What no app can undo.** The phone goes on trusting the key it "
             "paired with, in a list only root can edit, so it stays under "
             "*Wireless debugging → Paired devices*; remove it there with the "
             "gear beside it. Developer options stays on if you turned it on. And "
             "Start fresh leaves the one privileged setting granted, because "
             "handing it back would kill the app halfway through the reset."),

    ("h2", "Two honest warnings"),
    ("p", "**The other person is being recorded too.** Whether you may do that "
          "without telling them differs by country and sometimes by region. That "
          "is your call to make, not the app's."),
    ("p", "**This uses debugging switches, and they stay on.** They are developer "
          "features that let software on your phone act with elevated privileges. "
          "JemRec needs them to record calls at all. If you stop using JemRec, "
          "turn Wireless debugging, USB debugging and Developer options back off."),
]


def _inline_html(text: str) -> str:
    """The small Markdown subset the manual uses, as HTML."""
    out = (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<![*\w])\*([^*]+)\*(?!\w)", r"<em>\1</em>", out)
    return out


def render_html(blocks) -> str:
    """The manual as the page body."""
    out = []
    for kind, payload in blocks:
        if kind in ("h2", "h3"):
            # An id per heading, so the landing page can link straight to a
            # section rather than to the top of a long manual.
            anchor = re.sub(r"[^a-z0-9]+", "-", payload.lower()).strip("-")
            out.append(f'  <{kind} id="{anchor}">{_inline_html(payload)}</{kind}>')
        elif kind == "p":
            out.append(f"  <p>{_inline_html(payload)}</p>")
        elif kind in ("ol", "ul"):
            items = "".join(f"\n    <li>{_inline_html(i)}</li>" for i in payload)
            out.append(f"  <{kind}>{items}\n  </{kind}>")
        elif kind == "note":
            out.append(f'  <div class="note info"><p>{_inline_html(payload)}</p></div>')
        elif kind == "table":
            headers, rows = payload
            head = "".join(f"<th>{_inline_html(h)}</th>" for h in headers)
            body = "".join(
                "\n    <tr>" + "".join(f"<td>{_inline_html(c)}</td>" for c in r) + "</tr>"
                for r in rows
            )
            out.append(f"  <table>\n    <tr>{head}</tr>{body}\n  </table>")
        else:
            raise ValueError(f"unknown block: {kind}")
    return "\n".join(out)


def render_markdown(blocks) -> str:
    """The same manual as the file people read in the repository.

    Wrapped at 79 columns, because a Markdown file is read in an editor as often
    as in a browser and a paragraph on one endless line is unreadable in one of
    them.
    """
    out = []
    for kind, payload in blocks:
        if kind == "h2":
            out.append(f"## {payload}\n")
        elif kind == "h3":
            out.append(f"### {payload}\n")
        elif kind == "p":
            out.append(textwrap.fill(payload, 79) + "\n")
        elif kind == "ol":
            for n, item in enumerate(payload, 1):
                out.append(textwrap.fill(
                    item, 79, initial_indent=f"{n}. ", subsequent_indent="   "))
            out.append("")
        elif kind == "ul":
            for item in payload:
                out.append(textwrap.fill(
                    item, 79, initial_indent="- ", subsequent_indent="  "))
            out.append("")
        elif kind == "note":
            out.append(textwrap.fill(
                payload, 79, initial_indent="> ", subsequent_indent="> ") + "\n")
        elif kind == "table":
            headers, rows = payload
            out.append("| " + " | ".join(headers) + " |")
            out.append("|" + "|".join(["---"] * len(headers)) + "|")
            for row in rows:
                out.append("| " + " | ".join(c.replace("\n", " ") for c in row) + " |")
            out.append("")
    return "\n".join(out)


def shot(thumb: str, full: str, alt: str) -> str:
    """A screenshot that opens in the viewer.

    A button rather than an image with a click handler on it: it is a control,
    and the keyboard should be able to reach it and press it.
    """
    return (
        f'<button class="shot" type="button" data-full="{full}" aria-label="{alt}">'
        f'<img src="{thumb}" alt="{alt}" loading="lazy"></button>'
    )


def page(title: str, description: str, body: str, here: str) -> str:
    # A link to the page you are already on is furniture. The wordmark goes home
    # from anywhere, so Home only appears when you are somewhere else.
    def nav(href: str, label: str) -> str:
        return "" if href == here else f'<a href="{href}">{label}</a>'

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="color-scheme" content="light dark">
<link rel="icon" href="icon.png">
{HEAD_SCRIPT}
<link rel="stylesheet" href="jemrec.css">
<script src="jemrec.js" defer></script>
</head>
<body>
<header class="bar">
  <div class="column">
    <a class="brand" href="index.html"><img src="icon.png" alt="" width="34" height="34">JemRec</a>
    <div class="bar-end">
      <nav>{nav("index.html", "Home")}{nav("setup.html", "Setup")}{nav("privacy-policy.html", "Privacy")}<a href="{REPO}">GitHub</a></nav>
      {THEME_BUTTON}
    </div>
  </div>
</header>
<main>
{body}
</main>
<footer>
  <div class="column">
    <p>JemRec is free software under the Apache&nbsp;2.0 licence.
       <a href="{REPO}">Source on GitHub</a>.</p>
  </div>
</footer>
{VIEWER}
</body>
</html>
"""


# Both themes on the page at once, deliberately: the app follows the system
# setting and showing only one of them would hide half of what was drawn.
SHOTS = "\n    ".join([
    shot("screenshots/home.png", "screenshots/light/home.png", "The recordings list"),
    shot("screenshots/home-dark.png", "screenshots/dark/home.png", "The recordings list, dark"),
    shot("screenshots/settings.png", "screenshots/light/settings.png", "Settings"),
    shot("screenshots/selftest-dark.png", "screenshots/dark/selftest.png", "The self-test"),
])

INDEX_BODY = f"""
  <h1>{TAGLINE}</h1>
  <p class="lead">One APK. No root, no Shizuku, no companion app, and no computer
     &mdash; the phone pairs with its own Wireless debugging and sets itself up.</p>

  <div class="cta">
    <a class="btn" href="{REPO}/releases">Download the APK</a>
    <a class="btn ghost" href="{REPO}">Source on GitHub</a>
  </div>
  <p class="muted">Android 12 or newer. Not on Google Play, and never will be.
     Setting it up takes about three minutes and no computer &mdash;
     <a href="setup.html">here is how</a>. Play Protect sometimes objects to
     installing an app it has not seen before;
     <a href="setup.html#installing">the manual says what to do</a>.</p>

  <div class="note info">
    <p><strong>A reboot kills the recorder, and building it again takes a few
       seconds of Wi-Fi.</strong> Allow JemRec to start automatically in your
       phone's battery settings and it does that by itself &mdash; measured on an
       Honor, ten seconds after Wi-Fi came back, with the app never opened.
       Without that permission the phone will not start the app at boot at all,
       and you open it once instead.
       <a href="setup.html#after-a-restart">The manual has both measurements</a>.
       Wi-Fi rebuilds the recorder; it is never needed to use it.</p>
  </div>

  <div class="shots">
    {SHOTS}
  </div>
  <p class="muted">Tap any of them to look properly. The people in them do not
     exist: a screenshot of a call recorder is a screenshot of someone&rsquo;s
     calls, so the list is filled with invented ones. Everything above the list
     is real.</p>

  <h2>How it works</h2>

  <p>Android&rsquo;s <code>voice-call</code> audio source carries both sides of a
     call, and reading it needs permissions no ordinary app can hold &mdash; but
     the shell user, the one an ADB session runs as, holds them. Getting shell
     privilege normally means a computer, or root, or a second app you keep
     alive. JemRec needs none of them, because the phone can be its own
     computer.</p>

  <h3>The phone is both ADB host and ADB device</h3>
  <p>The app embeds an ADB client and pairs, over <code>127.0.0.1</code>, with
     the phone&rsquo;s own Wireless debugging &mdash; the same six-digit pairing a
     laptop does, with both ends on the same handset. Nothing leaves the phone.</p>

  <h3>ADB is a bootstrap, not a transport</h3>
  <p>That session lasts seconds. In it the app grants itself one settings
     permission and launches a small daemon from a jar it carries inside the APK,
     then closes the session. A process started from an ADB shell outlives the
     connection, which is the whole trick: with Wi-Fi off there is no ADB at all,
     so anything that needed it when a call arrived would simply not record.</p>

  <h3>The daemon records; the app collects</h3>
  <p>The daemon watches the call state and writes the call to a file. The app is
     never on the audio path. That split was forced by measurement: when the app
     handled live audio, the phone&rsquo;s process manager froze it while the
     dialer was in front and a 77-second call arrived as 14. Afterwards the app
     fetches the finished file at whatever pace the system allows, and a freeze
     there costs a slower copy rather than a lost second.</p>

  <h3>The socket is authenticated both ways</h3>
  <p>The daemon listens on loopback, which every process on the phone shares, so
     each connection proves itself with an HMAC exchange over a token that never
     crosses the socket. The daemon proves itself first &mdash; anything can bind
     that port while the daemon is down, and a scheme that sent the token as a
     password would hand it over.</p>

  <h3>It keeps itself alive</h3>
  <p>Losing Wi-Fi restarts the ADB daemon and kills what it spawned, so the
     recorder keeps one debugging switch on to survive it, and minds that switch
     itself. That is what lets a call be recorded in a field with no network.</p>
  <p>A reboot is the one thing it cannot survive, because starting the recorder
     is the single operation that needs ADB. A scheduled job and a system-held
     Wi-Fi watcher rebuild it without you within seconds of the phone joining a
     network &mdash; when the phone lets the app start in the background at boot
     to arm them. Where it does not, nothing is armed and nothing begins, which
     is why the manual says to open the app once after a restart. Either way the
     app says plainly that it cannot record rather than looking healthy.</p>

  <h2>What it asks for, and what it does not</h2>
  <p>No microphone permission. The app never opens an audio device &mdash; the
     shell-side process does the capturing &mdash; and a call recorder that asks
     for the microphone anyway is asking for something it does not use. Reading
     your call log and contacts is optional, offered once, and only labels a
     recording with who the call was with.</p>

  <div class="note">
    <p><strong>Recording calls is your responsibility.</strong> Consent law
       differs by country and sometimes by state: one party, all parties, or a
       spoken notice. This app records what you tell it to and warns nobody on
       your behalf.</p>
  </div>

  <h2>Will it work on your phone?</h2>
  <p>One thing cannot be worked around: whether your phone&rsquo;s audio hardware
     hands over the call at all. Some give both sides, some give one, some give
     silence. JemRec answers it in about a second &mdash; Settings, Diagnostics,
     <strong>Self-test</strong> &mdash; by opening a real capture down the same
     path a call takes and telling you what came out.</p>
  <p class="muted">Both sides of the call have been recorded on three phones,
     across three very different Android builds: an Honor Magic&nbsp;8 Pro on
     MagicOS&nbsp;10, a Samsung Galaxy&nbsp;S20 on One&nbsp;UI, and a OnePlus on
     LineageOS&nbsp;23. Three is not a compatibility list, which is what the
     self-test is for.</p>
"""

PRIVACY_BODY = f"""
  <h1>Privacy policy</h1>
  <p class="lead">JemRec has no servers, no accounts, and no analytics. Nothing it
     records or reads ever leaves your phone.</p>
  <p class="muted">Last updated: September 2026.</p>

  <h2>What it collects</h2>
  <p><strong>Nothing is sent anywhere.</strong> There is no backend to send it to.
     The developer cannot see your recordings, your contacts, your call history,
     or that you use the app at all.</p>

  <h2>What stays on the phone</h2>
  <table>
    <tr><th>Data</th><th>Where it lives</th></tr>
    <tr><td>Call recordings</td>
        <td>The phone&rsquo;s <code>Recordings/JemRec</code> folder, or a folder you
            choose. Yours to play, share, move or delete like any other file.</td></tr>
    <tr><td>Contact names and photos</td>
        <td>Read from the phone&rsquo;s own call log and contacts, only if you
            allow it, and only to label a recording. Nothing is copied or stored;
            the lookup happens each time the list is shown.</td></tr>
    <tr><td>Settings</td>
        <td>The app&rsquo;s own private storage: whether recording is on, whether to
            ask before each call, where to save, and a random token the app uses to
            talk to its own recorder.</td></tr>
  </table>

  <h2>Network use</h2>
  <p>The app holds the <code>INTERNET</code> permission and uses no network. Android
     requires that permission for <em>any</em> TCP socket, including one to
     <code>127.0.0.1</code>, and the app&rsquo;s two sockets are both to the phone
     itself: pairing with the phone&rsquo;s own Wireless debugging during setup, and
     talking to its recorder afterwards. Neither reaches your router, let alone the
     internet.</p>

  <h2>This website</h2>
  <p>Static files served by GitHub Pages, with no analytics, no cookies, and no
     fonts or scripts fetched from anywhere else. The one thing it stores is
     whether you chose light or dark, in your own browser, where it stays.</p>

  <h2>The microphone</h2>
  <p>The app holds no microphone permission and opens no audio device. Calls are
     captured by a separate shell-privileged process, which the app starts during
     setup and which writes to a file the app collects afterwards.</p>

  <h2>Deleting your data</h2>
  <p>Delete individual recordings in the app, or the whole folder from any file
     manager. <em>Start fresh</em> in Settings undoes the setup and hands the
     permissions back, and deliberately keeps your recordings. Uninstalling the app
     removes the app and its settings; the recordings stay, because they are yours
     and are not the app&rsquo;s to take.</p>

  <h2>Children</h2>
  <p>The app is not directed at children and collects nothing from anyone.</p>

  <h2>Changes</h2>
  <p>If this policy ever changes it changes
     <a href="{REPO}/blob/main/tools/build_site.py">in the open</a>, in the same
     repository as the code, with the change visible in the history.</p>

  <h2>Contact</h2>
  <p>Questions and bug reports: <a href="{REPO}/issues">GitHub issues</a>.</p>
"""


if __name__ == "__main__":
    DOCS.mkdir(parents=True, exist_ok=True)
    # Pages runs Jekyll by default, which ignores files beginning with an
    # underscore and would rather render Markdown than serve it. Nothing here
    # needs Jekyll.
    (DOCS / ".nojekyll").write_text("")
    (DOCS / "jemrec.css").write_text(CSS.replace("__DARK__", DARK_VARS))
    (DOCS / "jemrec.js").write_text(JS)
    (DOCS / "index.html").write_text(
        page(f"JemRec · {TAGLINE}", TAGLINE, INDEX_BODY, "index.html")
    )
    (DOCS / "setup.html").write_text(
        page(
            f"JemRec · {SETUP_TITLE}",
            "How to set up JemRec: three minutes, on the phone, no computer.",
            f'  <h1>{SETUP_TITLE}</h1>\n  <p class="lead">{SETUP_LEAD}</p>\n'
            + render_html(SETUP),
            "setup.html",
        )
    )
    # The same manual for whoever is reading the repository rather than the site.
    (DOCS / "SETUP.md").write_text(
        f"# {SETUP_TITLE}\n\n"
        + textwrap.fill(SETUP_LEAD, 79) + "\n\n"
        + "<!-- Generated by tools/build_site.py - edit the SETUP blocks there. -->\n\n"
        + render_markdown(SETUP)
    )
    (DOCS / "privacy-policy.html").write_text(
        page(
            "JemRec · Privacy policy",
            "JemRec has no servers and no analytics: nothing leaves your phone.",
            PRIVACY_BODY,
            "privacy-policy.html",
        )
    )
    for name in (".nojekyll", "jemrec.css", "jemrec.js", "index.html",
                 "setup.html", "privacy-policy.html", "SETUP.md"):
        print(f"wrote docs/{name}")
